version: '3'
services:
  ### PHP-FPM Container
  php-fpm:
    build: ./build/php-fpm
    volumes:
      - ./src:/var/www
    expose:
      - "9000"
    links:
      - mysql
      - redis
  
  ### NGINX Container
  nginx:
    build: ./build/nginx
    volumes:
      - ./logs/nginx/:/var/log/nginx
      - ./src:/var/www
    ports:
      - "15080:80"
      - "15443:443"
    links:
      - php-fpm

  ### MySQL Container
  mysql:
    build: ./build/mysql
    volumes:
      - /var/lib/mysql
    expose:
      - "3308"
    environment:
      MYSQL_DATABASE: lumen
      MYSQL_USER: daemon
      MYSQL_PASSWORD: 61a00XolJO4567r
      MYSQL_ROOT_PASSWORD: 123456

  ### Redis Container
  redis:
    image: redis
    expose:
        - "6379"

  ### Application Code Container
  application:
    build: ./build/application


  ### Workspace Utilities Container
  workspace:
    build: ./build/workspace
    volumes:
      - ./src:/var/www
    links:
      - mysql
      - redis
    tty: true

volumes:
  src: